training/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace training.Controllers
{
    public class SiteController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.NavClassIndex = "acctive1";
            return View();
        }

        public ActionResult Teach()
        {
            ViewBag.NavClassTeach = "acctive1";
            return View();
        }

        //Управление тренажёрами
        public ActionResult ManageTraining()
        {
            ViewBag.NavClassManageTrainigng = "acctive1";
            return View();
        }

        public ActionResult Poems()
        {
            ViewBag.NavClassLiric = "acctive1";
            return View();
        }

        public ActionResult Books()
        {
            ViewBag.NavClassLiric = "acctive1";
            return View();
        }

        public ActionResult Fit()
        {
            ViewBag.NavClassFit = "acctive1";
            return View();
        }

        public ActionResult Bn()
        {
            ViewBag.NavClassBn = "acctive1";
            return View();
        }
    }
}

training/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DatabaseFirst;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace training.Controllers
{
    public class TrainingController : Controller
    {
        // Создать объект контекста
        trainingsEntities context = new trainingsEntities();

        // GET: Training
        public System.Web.Mvc.ActionResult Index()
        {
            ViewBag.NavClassT = "acctive1";
            return View(context.trainings.AsQueryable().ToList());
        }

        public System.Web.Mvc.ActionResult ViewTraining(int id_tr)
        {
            ViewBag.NavClassT = "acctive1";
            DatabaseFirst.training training_ = context.trainings.AsQueryable().FirstOrDefault(g => g.id == id_tr);
            //здесь новая колонка 
            IEnumerable<DatabaseFirst.part> _p = context.parts.AsQueryable().OrderBy(g => g.order_id);//OrderByDescending(x => x.id)
            ViewData["part"] = _p.ToList();
            return View(training_);
        }


        public System.Web.Mvc.ActionResult testdialog()
        {
            return View();
        }



    }
}

training/Views/Shared/_Layout.cshtml
@helper CurrentItem(String item)
{
    if (item != ViewContext.RouteData.Values["action"].ToString())
    {
        return;
    }
    @:class="acctive1"
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Тренажеры по русскому языку</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />


    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/jquery-ui.css">
    <link rel="stylesheet" href="~/Content/balloon.css-master/balloon.min.css">
    @*<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>*@
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery-1.10.3.ui.min.js")
    @* @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")*@
    @Scripts.Render("~/bundles/bootstrap")
    @*<link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/flick/jquery-ui.css">*@
    <link href="~/Content/themes/flick/jquery-ui.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <style>
        .header1 {
            top: 0px;
            position: fixed;
            height: 72px;
            width: 100%;
            background-color: red; /*#43454e;*/
        }
    </style>
    <script>
        $(document).ready(function () {
            //    //Управление тренажёрами
            //if (User.IsInRole("Учитель")) {
            //    document.getElementById('righter').style.marginLeft = 5 + "%";
            //    document.getElementById("righter").style.marginTop = -3 + "%";
            //}
            //else {
            //    document.getElementById('righter').style.marginLeft = 0 + "%";
            //    document.getElementById("righter").style.marginTop = 1 + "%";
            //}
            var header = $(".header");
            var scrollPrev = 0; // Предыдущее значение скролла

            $(window).scroll(function () {
                var a = $(window).scrollLeft();
                var b = $(window).scrollTop();
                if (a > 0) {
                    document.getElementsByClassName('header')[0].style.position = 'fixed';
                    document.getElementsByClassName('header')[0].style.backgroundColor = '#43454e';
                    document.getElementsByClassName('header')[0].style.height = "72px";
                    if (b > 50) { document.getElementsByClassName('header')[0].style.display = 'none'; }
                    else { document.getElementsByClassName('header')[0].style.display = 'block'; }
                }
                else {
                    // $('.header').removeClass('header1');
                    document.getElementsByClassName('header')[0].style.position = 'absolute';
                    document.getElementsByClassName('header')[0].style.backgroundColor = '#43454e';
                    document.getElementsByClassName('header')[0].style.height = "72px";
                    document.getElementsByClassName('header')[0].style.display = 'block';
                }
            });
        });
    </script>
    @* <div id="h1" style="display:block;top:0;height:72px;background-color:#43454e;width:10000px;position:absolute;float:left; overflow:hidden"></div>*@
    <div class="header" style="width:100%"></div>
    <div class="logo-menu">
        @*<div class="Rectangle" style="z-index:-1000; top:0;width:100%;position:absolute"></div>*@
        <nav class="Rectangle">
            <div class="container" id="body_center">
                <!-- Brand and toggle get grouped for better mobile display min_haight -->
                <div class="navbar-header" id="header_center" style="position:relative">
                    <a class="navbar-brand" href="@Url.Action("Index", "Site")">
                        <img src="/img/invalid-name.png" class="layer">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbar">
                    @*Управление тренажёрами*@
                    @if (User.IsInRole("Учитель")||(User.IsInRole("Владелец")))
                    {
                        <ul class="ter nav navbar-nav navbar-left" id="righter" style="margin-left:5%;margin-top:-3.5%;white-space: nowrap;">
                            <li class="@ViewBag.NavClassIndex"><a href=@Url.Action("Index", "Site")>Обо мне</a></li>
                            <li class="@ViewBag.NavClassT"><a href=@Url.Action("Index", "Training")>Тренажеры</a></li>

                            <li class="@ViewBag.NavClassManageTraining"><a href=@Url.Action("Index", "Teacher")>Управление тренажерами</a></li>

                            <li class="@ViewBag.NavClassTeach"><a href=@Url.Action("Teach", "Site")>Учителю</a></li>
                            <li class="@ViewBag.NavClassFit"><a href=@Url.Action("Fit", "Site")>Материалы о Тютчеве</a></li>
                            <li class="@ViewBag.NavClassLiric">
                                <a href=@Url.Action("Books", "Site")>Лирика</a>
                                <ul class="submenu">
                                    <li><a href=@Url.Action("Books", "Site")>Книги</a></li>
                                    <li><a href=@Url.Action("Poems", "Site")>Поэмы</a></li>
                                    <li></li>
                                </ul>
                            </li>
                            <li class="@ViewBag.NavClassBn"><a href=@Url.Action("Bn", "Site")>Борис Непомнящий </a></li>
                        </ul>
                    }
                    @* /////////////////////////////// *@
                    else  {
                    <ul class="ter nav navbar-nav navbar-left" style="white-space: nowrap;">
                        <li class="@ViewBag.NavClassIndex"><a href=@Url.Action("Index", "Site")>Обо мне</a></li>
                        <li class="@ViewBag.NavClassT"><a href=@Url.Action("Index", "Training")>Тренажеры</a></li>
                        <li class="@ViewBag.NavClassTeach"><a href=@Url.Action("Teach", "Site")>Учителю</a></li>
                        <li class="@ViewBag.NavClassFit"><a href=@Url.Action("Fit", "Site")>Материалы о Тютчеве</a></li>
                        <li class="@ViewBag.NavClassLiric">
                            <a href=@Url.Action("Books", "Site")>Лирика</a>
                            <ul class="submenu">
                                <li><a href=@Url.Action("Books", "Site")>Книги</a></li>
                                <li><a href=@Url.Action("Poems", "Site")>Поэмы</a></li>
                                <li></li>
                            </ul>
                        </li>
                        <li class="@ViewBag.NavClassBn"><a href=@Url.Action("Bn", "Site")>Борис Непомнящий </a></li>
                    </ul>
                    }
                </div>
            </div>
        </nav>
    </div>

    <div class="container1" style="min-width:900px">
        @RenderBody()

    </div>
    <footer>
        <div class="Rectangle_bottom"></div>
    </footer>
  
    @RenderSection("scripts", required: false)



</body>
</html>

training/Views/Shared/_answer.cshtml
<div class="form-group row wordDiv">
    <label for="answer" class="col-sm-4 col-form-label wordLabel">Слово-ответ</label>
    <div class="col-sm-4 wordDivInput">
        <input maxlength="30" type="text" placeholder="нами" class="form-control js-syllMirror-word-answer morphii wordInput" id="answer" onkeypress="return testAnswer(event)" onchange="wordToBonus()">
    </div>
    <button tabIndex="-1" type="button" class="btn btn-light btn-circle wordBtn" style="border-radius:50%;border:0;outline: none;" data-toggle="popover" data-content="Введите слово-ответ, составленное из слогов предыдущего слова. Например, для слова 'мина' словом-ответом будет 'нами'">?</button>
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover({
                placement: 'top'
            });
        });
    </script>
</div>
<div class="form-group row phoneticDiv">
    <label for="phonetic2" class="col-sm-4 col-form-label pnoneticLabel">Фонетическая <br /> запись слова</label>
    <div class="col-sm-4">
        <input maxlength="30" type="text" placeholder="на-м'и" class="form-control js-syllMirror-word-answer-phonetic phoneticInput" id="phonetic2" name="secondInput" onkeypress="return testPhonetic(event)">
    </div>
    <button tabIndex="-1" type="button" class="btn btn-light btn-circle phoneticBtn" style="border-radius:50%;border:0;outline: none;" data-toggle="popover" data-content="Введите фонетическую запись. Для разделения слогов используйте знак -, для мягкости '. Вместо апострофа можно вводить точку, запятую, цифру 8 или символ *">?</button>
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover({
                placement: 'top'
            });
        });
    </script>
</div>
<div class="form-group row primaryDiv" style="height:50px;margin-top:-10px;">
    <label for="answerPrimary" class="col-sm-4 col-form-label primaryLabel" id="answerPrimaryLabel">Начальная <br /> форма слова</label>
    <div class="col-sm-4" id="answerPrimary">
        <input maxlength="30" type="text" placeholder="мы" id="answerPrimaryInput" name="answerPrimaryInput" class="form-control primaryInput" onkeypress="return testPrimary(event)">
    </div>
    <button tabIndex="-1" type="button" class="btn btn-light btn-circle primaryBtn" style="border-radius:50%;border:0;outline: none;" data-toggle="popover" data-content="Введите инфинитив. Примеры инфинитивов - верить, великолепный, дорога. Если слово неизменяемое, введите символ -">?</button>
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover({
                placement: 'top'
            });
        });
    </script>
</div>
<div class="form-group row contextDiv" style="margin-top:-3%">
    <label class="col-sm-4 col-form-label contextLabel">Контекст</label>
    <div class="col-sm-7 contextDivInput">
        <input maxlength="50" type="text" placeholder="Нами проделана работа." class="form-control contextInput" id="contextAnswer" onchange="contextToBonus()">
    </div>
</div>
@Html.Partial("_parts")
<div class="js-word-answer-morphem morphologyDiv" style="display:none;">
    @Html.Partial("_styllMirrorMorphology")
</div>

training/Views/Shared/_lexicology2.cshtml
<h1 id="otcomment" style="text-align:center; margin-top:-1%;margin-left:-5%">Откомментируй</h1>
@*<h3 style="margin-left:38%;margin-right:20%; margin-bottom:2%">Слова-ответы являются</h3>*@
<div style="margin-left:22%">
    <div style="margin-left:30%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika" class="lexic2_12 L">@item.name<Br>
        }
    </div>
    <div style="width:auto; margin-left:22%; margin-top:-5%">
        <div class="forLexic" id="answerL" style="display:inline; width:10%;height:10%;font-size:18px; text-align:center"></div> @*<hr style="width:200px; display:inline-block; border: 0; border-top: 2px solid #8c8c8c;border-bottom: 1px solid #fff;" />*@
        <canvas width="110" height="80" style="display:inline-block;" id="canvas10"></canvas>
        <div class="forLexic" id="answer2L" style="display:inline; width:10%;height:10%; text-align:center;font-size:18px"></div>
        <div style="vertical-align:bottom;top:0;width:auto;">
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%;display:inline"></div>
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%; display:inline"></div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        var lexicText1 = document.getElementsByClassName('forLexicText')[0];
       
       // lexicText1.style.marginLeft = (parseFloat(answerL.style.marginLeft).toString())+ "px";
        var cnvs = document.getElementById("canvas10"); 
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(55, 130, 75, 1.25 * Math.PI, 1.75 * Math.PI, false);
        ctxt.stroke();
    });
</script>

training/Views/Shared/_lexicology3.cshtml
<h1 id="otcomment" style="text-align:center;margin-top:-1%">Откомментируй</h1>
<div style="margin-left:22%">
    <div style="margin-left:20%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika" class="lexic3_12 L L3">@item.name<Br>
        }
    </div>
    <div style="margin-left:45%; margin-top:-11.7%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika2" class="lexic3_23 L L3">@item.name<Br>
        }
    </div>
    <div style="width:auto; margin-left:10%;margin-top:-5%">
        <div class="forLexic" id="answerL0" style="display:inline; width:10%;height:10%;font-size:18px; text-align:center; ">
        </div>
        <canvas width="110" height="80" style="display:inline-block;" id="canvas0"></canvas>
        <div class="forLexic" id="answer2L0" style="display:inline; width:10%;height:10%; text-align:center;font-size:18px"></div>
        <canvas width="110" height="80" style="display:inline-block;" id="canvas20"></canvas>
        <div class="forLexic" id="answer3L0" style="display:inline; width:10%;height:10%; text-align:center;font-size:18px"></div>
        <div style="vertical-align:bottom;top:0;width:auto;">
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%;display:inline"></div>
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%; display:inline"></div>
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%; display:inline"></div>
        </div>
        <canvas width="450" height="80" style="display:inline-block;margin-top:-5%" id="canvas30"></canvas>
    </div>
    <div style="margin-left:33%;" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika3" class="lexic3_13 L L3">@item.name<Br>
        }
    </div>
</div>
<script>
    $(document).ready(function () {
        var firstWidth;
        var cnvs = document.getElementById("canvas0");
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(55, 130, 75, 1.25 * Math.PI, 1.75 * Math.PI, false);
        ctxt.stroke();
        var cnvs = document.getElementById("canvas20");
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(55, 130, 75, 1.25 * Math.PI, 1.75 * Math.PI, false);
        ctxt.stroke();
        firstWidth = document.getElementById("answer2L0").offsetWidth;
        var cnvs = document.getElementById("canvas30");
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(195 + firstWidth / 10, -261, 340, 0.35 * Math.PI, 0.65 * Math.PI, false);
        ctxt.stroke();
    });
</script>

training/Views/Shared/_lexicology4.cshtml
<h1 id="otcomment" style="text-align:center;margin-top:-1%">Откомментируй</h1>
<div style="margin-left:2%; margin-bottom:3%">
    <div style="margin-left:36.5%; margin-top:0%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika" class="lexic4_12 L L4">@item.name<Br>
        }
    </div>
    <div style="margin-left:47.5%; margin-top:-5.7%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika2" class="lexic4_23 L L4">@item.name<Br>
        }
    </div>
    <div style="margin-left:58%; margin-top:-5.8%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika3" class="lexic4_34 L L4">@item.name<Br>
        }
    </div>
    <div style="width:auto; margin-left:31%;margin-top:-3%">
        <div class="forLexic" id="answerL1" style="display:inline; width:10%;height:10%;font-size:18px; text-align:center; ">
        </div>
        <canvas width="110" height="80" style="display:inline-block;" id="canvas00"></canvas>
        <div class="forLexic" id="answer2L1" style="display:inline; width:10%;height:10%; text-align:center;font-size:18px"></div>
        <canvas width="110" height="80" style="display:inline-block;" id="canvas200"></canvas>
        <div class="forLexic" id="answer3L1" style="display:inline; width:10%;height:10%; text-align:center;font-size:18px"></div>
        <canvas width="110" height="80" style="display:inline-block;" id="canvas400"></canvas>
        <div class="forLexic" id="answer4L1" style="display:inline; width:10%;height:10%; text-align:center;font-size:18px"></div>
        <div style="vertical-align:bottom;top:0;width:auto;">
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%;display:inline"></div>
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%; display:inline"></div>
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%; display:inline"></div>
            <div class="forLexicText" style="vertical-align:bottom;top:0;width:10%; display:inline"></div>
        </div>
        <canvas width="450" height="80" style="display:inline-block;margin-top:-3%;" id="canvas300"></canvas>
        <canvas width="450" height="80" style="display:inline-block;margin-top:-5%;margin-left:-30%" id="canvas500"></canvas>
        <canvas width="650" height="600" style="display:inline-block;margin-top:-5%;" id="canvas600"></canvas>
    </div>

    <div style="margin-left:41%;margin-top:-36.5%" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika4" class="lexic4_13 L L4">@item.name<Br>
        }
    </div>
    <div style="margin-left:54%;margin-top:-5.8%;" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika5" class="lexic4_24 L L4">@item.name<Br>
        }
    </div>
    <div style="margin-left:47%; margin-top:5%;" class="radio">
        @foreach (var item in ViewData["lexic"] as List<DatabaseFirst.lexic>)
        {
            <input type="radio" name="lexika6" class="lexic4_14 L L4">@item.name<Br>
        }
    </div>
</div>
<script>
    $(document).ready(function () {




        var firstWidth;
        var cnvs = document.getElementById("canvas00");
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(55, 130, 75, 1.25 * Math.PI, 1.75 * Math.PI, false);
        ctxt.stroke();

        var cnvs = document.getElementById("canvas200");
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(55, 130, 75, 1.25 * Math.PI, 1.75 * Math.PI, false);
        ctxt.stroke();

        var cnvs = document.getElementById("canvas400");
        var ctxt = cnvs.getContext("2d");
        ctxt.strokeStyle = "darkgrey";
        ctxt.lineWidth = 3;
        ctxt.arc(55, 130, 75, 1.25 * Math.PI, 1.75 * Math.PI, false);
        ctxt.stroke();

        firstWidth = document.getElementById("answer2L1").offsetWidth;
        var cnvs20 = document.getElementById("canvas300");
        var ctxt20 = cnvs20.getContext("2d");
        ctxt20.strokeStyle = "darkgrey";
        ctxt20.lineWidth = 3;
        ctxt20.arc(195 + firstWidth / 10, -261, 340, 0.35 * Math.PI, 0.65 * Math.PI, false);
        ctxt20.stroke();

        secondWidth = document.getElementById("answer3L1").offsetWidth;
        var cnvs1 = document.getElementById("canvas500");
        var ctxt1 = cnvs1.getContext("2d");
        ctxt1.strokeStyle = "darkgrey";
        ctxt1.lineWidth = 3;
        ctxt1.arc(195 + firstWidth / 10, -261, 340, 0.35 * Math.PI, 0.65 * Math.PI, false);
        ctxt1.stroke();
      
        firstWidth = document.getElementById("answer2L1").offsetWidth;
        secondWidth = document.getElementById("answer3L1").offsetWidth;
        thirdWidth = document.getElementById("answer4L1").offsetWidth;
        var cnvs = document.getElementById("canvas600");
        var ctx = cnvs.getContext("2d");
        ctx.strokeStyle = "darkgrey";
        ctx.lineWidth = 3;
        ctx.beginPath();
        ctx.moveTo(50, 10);
        ctx.quadraticCurveTo((255 + secondWidth / 10 + firstWidth), 600, (200 + secondWidth / 10 + thirdWidth / 10 + firstWidth) + (200 + secondWidth / 10 + firstWidth) * 1.4, 10);
        ctx.stroke();
        ctx.closePath();
    });
</script>

training/Views/Shared/_morphems.cshtml
<h1 style="text-align:center">Сделай разбор по составу</h1>
<h4 style="margin-bottom:2%;text-align:center">Для разделения частей слова используй знак <i>дефис</i> (-). Для обозначения нулевого окончания в конце слова поставь <i>дефис</i> после всех букв. Если нулевое окончание находится не в конце слова, то поставь два <i>дефиса</i> подряд. Например, разбор слова "снился" будет выглядеть так:"сн-и-л--ся"</h4>
<ul style="text-align:center" class="morphemBonusUl">
    <li class="morphemBonusLi" style="display: inline-block;text-align: left; margin-right:2%">
        <div class="morphemBonusDivs">
            <input maxlength="30" id="wordML" type="text" class="form-control js-syllMirror-word-morphems morphemBonusInputs forMorphii" onkeypress="testMorphem(event)">
            <div class="morphContext"><br /></div>
        </div>
    </li>
    <li class="morphemBonusLi" style="display: inline-block;  text-align: left;margin-right:2%">
        <div class="morphemBonusDivs">
            <input maxlength="30" id="answerML" type="text" class="form-control js-syllMirror-answer-morphems morphemBonusInputs forMorphii" onkeypress="testMorphem(event)">
            <div class="morphContext"><br /></div>
        </div>
    </li>
    <li class="morphemBonusLi" style="display: none;text-align: left; margin-right:2%">
        <div class="morphemBonusDivs">
            <input maxlength="30" id="answer2ML" type="text" class="form-control js-syllMirror-answer2-morphems morphemBonusInputs forMorphii" onkeypress="testMorphem(event)">
            <div class="morphContext"><br /></div>
        </div>
    </li>
    <li class="morphemBonusLi" style="display:none;text-align: left; margin-right:2%">
        <div class="morphemBonusDivs">
            <input maxlength="30" id="answer3ML" type="text" class="form-control js-syllMirror-answer3-morphems morphemBonusInputs forMorphii" onkeypress="testMorphem(event)">
            <div class="morphContext"><br /></div>
        </div>
    </li>
    <li class="morphemBonusLi" style="display:none;text-align: left; margin-right:2%">
        <div class="morphemBonusDivs">
            <input maxlength="30" id="answer4ML" type="text" class="form-control js-syllMirror-answer4-morphems morphemBonusInputs forMorphii" onkeypress="testMorphem(event)">
            <div class="morphContext"><br /></div>
        </div>
    </li>
    <li style=" width: 100%;
                height: 0;
                visibility: hidden;"></li>
</ul>
<script>
   function testMorphem(event) {
        event = event || window.event;
        if (event.charCode && (event.charCode != 45)) { var obj = event.target || event.srcElement; redInput(obj); return false; }
    };
</script>

training/Views/Shared/_parts.cshtml
<fieldset class="form-group row chooseFieldset">
    <legend class="col-form-legend col-sm-6 chooseLegend">Выберите часть речи</legend>
    <div class="col-sm-10">
        <div class="radio_buttons rb1 chooseDiv">
            @foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                <div class="form-check-label chooseDivLabel">
                    <label class="chooseLabel">
                        <input class="js-radio-word-answer chooseInput" type="radio" name="optradio1" value="@item.id">
                        @item.name
                    </label><br />
                </div>
            }
        </div>
    </div>
</fieldset>