training/Controllers/ExerciseController.cs
using DatabaseFirst;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace training.Controllers
{
    public class ExerciseController : Controller
    {
        List<int> ListIdExer = new List<int>();
        trainingsEntities context = new trainingsEntities();
        public ActionResult ExerciseOne(int id_t, int level, int id_tr)
        {
            ViewBag.NavClassT = "acctive1";

            int i = 0;
            DatabaseFirst.syll_mirror exer;
            DatabaseFirst.Them _t = context.Thems.Where(t => t.id_training == id_tr).Where(t => t.id_part == id_t).Where(t => t.level == level).FirstOrDefault();
            try
            {
                int id1 = _t.id_exercise;
                exer = context.syll_mirror.Where(t => t.id == id1 && t.level == level).FirstOrDefault();
                while (exer == null)
                {
                    id1++;
                    exer = context.syll_mirror.Where(t => t.id == id1 && t.level == level).FirstOrDefault();
                }
                word w = context.words.FirstOrDefault(n => n.id == exer.id_word);
                word w2 = context.words.FirstOrDefault(n => n.id == exer.id_answer1);
                ViewData["word1"] = w.word1;
                ViewData["word2"] = w2.word1;
                ViewData["context1"] = w.context;
                IEnumerable<DatabaseFirst.part> _p = context.parts.AsQueryable();
                ViewData["part"] = _p.ToList();
                IEnumerable<DatabaseFirst.comment> _c = context.comments.AsQueryable();
                ViewData["com"] = _c.ToList();
                ViewData["nextWord"] = id_t;
                ViewData["realLevel"] = level;
                ViewData["morphemWord"] = w.morphems;
                ViewData["morphemAnswer1"] = w2.morphems;
                ViewData["id_tr"] = id_tr;
                List<char> zz = w.word1.ToList();
                return View(exer);
            }
            catch (System.Exception exc) { exer = null; return View(exer); }
        }

        public ActionResult doError(int b)
        {
            var a = 1 / b;
            DatabaseFirst.syll_mirror exer;
            exer = context.syll_mirror.FirstOrDefault();
            return View(exer);
        }

        public ActionResult ExerciseTwo(int id_t, int level, int id_tr)
        {
            ViewBag.NavClassT = "acctive1";

            int i = 0;
            DatabaseFirst.syll_mirror exer;
            DatabaseFirst.Them _t = context.Thems.Where(t => t.id_training == id_tr).Where(t => t.id_part == id_t).Where(t => t.level == level).FirstOrDefault();
            try
            {
                int id1 = _t.id_exercise;
                exer = context.syll_mirror.Where(t => t.id == id1 && t.level == level).FirstOrDefault();
                while (exer == null)
                {
                    id1++;
                    exer = context.syll_mirror.Where(t => t.id == id1 && t.level == level).FirstOrDefault();
                }
                word w = context.words.FirstOrDefault(n => n.id == exer.id_word);
                word w2 = context.words.FirstOrDefault(n => n.id == exer.id_answer1);
                word w3 = context.words.FirstOrDefault(n => n.id == exer.id_answer2);

                ViewData["word1"] = w.word1;
                ViewData["word2"] = w2.word1;
                ViewData["word3"] = w3.word1;


                ViewData["context2"] = w.context;
                IEnumerable<DatabaseFirst.part> _p = context.parts.AsQueryable();
                ViewData["part"] = _p.ToList();
                IEnumerable<DatabaseFirst.comment> _c = context.comments.AsQueryable();
                ViewData["com"] = _c.ToList();
                ViewData["nextWord"] = id_t;
                ViewData["realLevel"] = level;
                ViewData["morphemWord"] = w.morphems;
                ViewData["morphemAnswer1"] = w2.morphems;
                ViewData["morphemAnswer2"] = w3.morphems;


                //3 ответ
                ViewData["3answer"] = null;
                try
                {
                    word w4 = context.words.FirstOrDefault(n => n.id == exer.id_answer3);
                    ViewData["word4"] = w4.word1;
                    ViewData["morphemAnswer3"] = w4.morphems;
                    ViewData["3answer"] = "3answer";
                }
                catch (System.Exception exc) { int abcdef1 = 0; }

                //4 ответ
                ViewData["4answer"] = null;
                try
                {
                    word w5 = context.words.FirstOrDefault(n => n.id == exer.id_answer4);
                    ViewData["word5"] = w5.word1;
                    ViewData["morphemAnswer4"] = w5.morphems;
                    ViewData["4answer"] = "4answer";
                }
                catch (System.Exception exc) { int abcdef2 = 0; }


                ViewData["lexic"] = context.lexics.AsQueryable().ToList();
                ViewData["id_tr"] = id_tr;
                return View(exer);
            }
            catch (System.Exception exc) { exer = null; return View(exer); }
        }
        public ActionResult GetMorphologyByWordId(int wordId)
        {
            var word = context.words.FirstOrDefault(item => item.id == wordId);
            if (word == null)
            {
                return Json(new { Type = "Error" }, JsonRequestBehavior.AllowGet);
            }


            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            var converted = JsonConvert.SerializeObject(word.morphology, null, jsSettings);

            return Json(new { Type = "Success", Data = JsonConvert.SerializeObject(word.morphology, null, jsSettings) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSyllMirrorWordsByLevel(int level, int pId, int id_tr)
        {
            var syllMirrorWords = context.nextViews.Where(t => t.id_training == id_tr).Where(item => item.level == level).Where(item => item.id_part == pId).Select(p => new
            {
                id = p.id,
                id_exercise = p.id_exercise,
                id_word = p.id_word,
                id_answer1 = p.id_answer1,
                id_answer2 = p.id_answer2,

                //3 ответ
                id_answer3 = p.id_answer3,

                //4 ответ
                id_answer4 = p.id_answer4,

                level = p.level
            }).ToList();

            if (syllMirrorWords.Count == 0)
            {
                return Json(new { Type = "Error" }, JsonRequestBehavior.AllowGet);
            }

            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;


            var data = JsonConvert.SerializeObject(syllMirrorWords, null, jsSettings);

            return Json(new { Type = "Success", Data = data }, JsonRequestBehavior.AllowGet);
        }

        public class AddProgressModel
        {
            public int mark { get; set; }
            public int id_exercise { get; set; }
        }
        [HttpPost]
        public ActionResult sendMarkToServer(AddProgressModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                progress entity = new progress
                {
                    id_user = User.Identity.GetUserId(),
                    id_exercice = model.id_exercise,
                    mark = model.mark
                };

                var a = context.progresses.Add(entity);
                context.SaveChanges();
                JsonSerializerSettings jsSettings = new JsonSerializerSettings();
                jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                return Json(new { Type = "Success", Data = JsonConvert.SerializeObject(a, null, jsSettings) }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return View();
            }
        }

        public ActionResult GetListParts()
        {
            var lp = context.part1.AsEnumerable();
            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            return Json(new { Type = "Success", Data = JsonConvert.SerializeObject(lp, null, jsSettings) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult loadMorphologyWord(int id_word)
        {
            var morphology = context.morphology_view.Where(p => p.id == id_word).FirstOrDefault();
            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            return Json(new { Type = "Success", Data = JsonConvert.SerializeObject(morphology, null, jsSettings) }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult loadMorphologyAnswer(int id_answer)
        {
            var morphology = context.morphology_view.Where(p => p.id == id_answer).FirstOrDefault();
            JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            return Json(new { Type = "Success", Data = JsonConvert.SerializeObject(morphology, null, jsSettings) }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult loadLexic(int id_e)
        {
            //var lexic = context.lexic_view.Where(p => p.level == id_e).FirstOrDefault();
            //JsonSerializerSettings jsSettings = new JsonSerializerSettings();
            //jsSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            //return Json(new { Type = "Success", Data = JsonConvert.SerializeObject(lexic, null, jsSettings) }, JsonRequestBehavior.AllowGet);

training/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DatabaseFirst;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace training.Controllers
{
    public class TrainingController : Controller
    {
        // Создать объект контекста
        trainingsEntities context = new trainingsEntities();

        // GET: Training
        public System.Web.Mvc.ActionResult Index()
        {
            ViewBag.NavClassT = "acctive1";
            return View(context.trainings.AsQueryable().ToList());
        }

        public System.Web.Mvc.ActionResult ViewTraining(int id_tr)
        {
            ViewBag.NavClassT = "acctive1";
            DatabaseFirst.training training_ = context.trainings.AsQueryable().FirstOrDefault(g => g.id == id_tr);
            //здесь новая колонка 
            IEnumerable<DatabaseFirst.part> _p = context.parts.AsQueryable().OrderBy(g => g.order_id);//OrderByDescending(x => x.id)
            ViewData["part"] = _p.ToList();
            return View(training_);
        }


        public System.Web.Mvc.ActionResult testdialog()
        {
            return View();
        }



    }
}

training/Views/Training/Index.cshtml
@model IEnumerable<DatabaseFirst.training>

@{
    ViewBag.Title = "Training";
}
<div class="row">
    <div class="col-md-12">
        @Html.Partial("_LoginPartial")
    </div>
</div>
        <div style="text-align:center; color: #638289; margin-bottom:3%"><h1>Раздел находится в разработке.</h1></div>
<ul class="c-tile-list">
    @foreach (var item in Model)
    {
        <li class="c-tile-list__item">
            <article class="c-article-tile t-sass">
                <!-- шапка -->
                <div class="c-article-tile__header">
                    <div class="c-article-tile__category">
                        @Html.ActionLink(@item.name, "ViewTraining", new { id_tr = item.id })
                    </div>
                </div>
                <div class="c-article-tile__body">
                    <div class="c-article-tile__title" itemprop="headline">

                        @item.description

                    </div>
                </div>
            </article>
        </li>

    }
</ul>

training/Views/Training/ViewTraining.cshtml
@model DatabaseFirst.training
@{
    ViewBag.Title = "ViewTrainng";
}
<div class="row">
    <div class="col-md-12">
        @Html.Partial("_LoginPartial")
    </div>
</div>
<div class="row">
    <h1 style="padding-left:12px">@Model.name</h1>

    <div class="col-md-2">
        <section>
            @*@if (Model.id == 1||M)
            {*@
                <div>О тренажере</div>
            @* } *@
        </section>
    </div>
    <div class="col-md-10" style="padding-left:7%;padding-right:10%;">
        @if (Model.id == 1)
        {
            <div style="margin-left:-34%;margin-top:5%; margin-bottom:3%">
                «Слоговое зеркало» обращает внимание ученика на принципы слогоделения, обучает учитывать семантические и звуковые допуски для создания конвергента. При нахождении ответа в данном тренажере активизируются знания по словообразованию и морфологии.
            </div>
            <div style="text-align:center; margin-left:-15%; border-bottom:inset">1 уровень</div>
            foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                //<div style="background-color:aliceblue; border-color:cadetblue;border-width:medium;border-style:ridge; border-radius:20px; margin-left:2%;margin-top:2%; padding:30px; width:25%;text-align:center;">
                @Html.ActionLink(@item.name, "ExerciseOne", "Exercise", new { id_t = item.id, level = 1, id_tr = Model.id }, new { @class = "btn btn-success btn-lg levelClass" })
                //  </div>
            }
            <div style="text-align:center; margin-left:-15%; border-bottom:inset">2 уровень</div>
            foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                //<div style="background-color:aliceblue; border-color:cadetblue;border-width:medium;border-style:ridge; border-radius:20px; margin-left:2%;margin-top:2%; padding:30px; width:25%;text-align:center;">
                @Html.ActionLink(@item.name, "ExerciseTwo", "Exercise", new { id_t = item.id, level = 2, id_tr = Model.id }, new { @class = "btn btn-success btn-lg levelClass" })
                //  </div>
            }
        }
        @if (Model.id == 2)
        {
            <div style="margin-left:-34%;margin-top:5%; margin-bottom:3%">
                «Звуковое зеркало» служит для привлечения внимания учеников к различиям «звучание-написание». Обращается внимание на необходимость знаний акустических и артикуляционных характеристик, изменений звука в зависимости от места в слове, от рядом стоящих звуков.
            </div>
            <div style="text-align:center; margin-left:-15%; border-bottom:inset">1 уровень</div>
            foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                @Html.ActionLink(@item.name, "ExerciseOne", "Exercise", new { id_t = item.id, level = 1, id_tr = Model.id }, new { @class = "btn btn-success btn-lg levelClass" })
            }
            <div style="text-align:center; margin-left:-15%; border-bottom:inset">2 уровень</div>
            foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                @Html.ActionLink(@item.name, "ExerciseTwo", "Exercise", new { id_t = item.id, level = 2, id_tr = Model.id }, new { @class = "btn btn-success btn-lg levelClass" })
            }
        }
        @if (Model.id == 1007)
        {
            <div style="margin-left:-34%;margin-top:5%; margin-bottom:3%;">
                «Узнай в лицо» помогает привлечь внимание учащихся к межуровневым языковым связям.Формирует у учеников представления о фонетическом слове и тренирует знания фонетики, словообразования и морфологии.
            </div>
            <div style="text-align:center; margin-left:-15%; border-bottom:inset">1 уровень</div>
            foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                @Html.ActionLink(@item.name, "ExerciseOne", "Exercise", new { id_t = item.id, level = 1, id_tr = Model.id }, new { @class = "btn btn-success btn-lg levelClass" })
            }
            <div style="text-align:center; margin-left:-15%; border-bottom:inset">2 уровень</div>
            foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                @Html.ActionLink(@item.name, "ExerciseTwo", "Exercise", new { id_t = item.id, level = 2, id_tr = Model.id }, new { @class = "btn btn-success btn-lg levelClass" })
            }
        }
        @*<div class="col-md-8" style="display:flex; flex-direction:row; align-items:stretch; justify-content:center; flex-wrap:wrap; ">*@
        @*<label>Темы</label>
        <ul>
            @foreach (var item in ViewData["part"] as List<DatabaseFirst.part>)
            {
                <li>@Html.ActionLink(@item.name, "ExerciseOne", "Exercise", new { id_t = item.id, k = true }, null)</li>
            }
        </ul>
        <label>Уровни</label>
        <ul>
            <li>@Html.ActionLink("1 уровень", "ExerciseOne", "Exercise", new { id_t = 1, k = false }, null)</li>
            <li>@Html.ActionLink("2 уровень", "ExerciseTwo", "Exercise", new { id_t = 2, k = false }, null)</li>
        </ul>*@
        <div style="margin-bottom:10%"></div>
    </div>
</div>

training/Views/Training/testdialog.cshtml
@{
    ViewBag.Title = "testdialog";
}

<h2>testdialog</h2>

<script>
  var s = (function() {
    $("#dialog").dialog();
  } );

</script>

<div id="dialog" title="Basic dialog">
    <p>This is the default dialog which is useful for displaying information. The dialog window can be moved, resized and closed with the 'x' icon.</p>
</div>